### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by coisnepe** [akashsara/whatsapp-message-analysis#3]
Hey,

Thanks for putting this together!

Just tried to run your script on one of my conversations and I'm running into the following error. Any idea of what might be happening?

Thanks for your help
```
Traceback (most recent call last):
  File "analyze.py", line 261, in <module>
    driver()
  File "analyze.py", line 228, in driver
    'output/' + file_name + '-time_activity.png'
  File "whatsapp-message-analysis/graphs.py", line 32, in histogram
    y=list(dictionary.values())
  File "/usr/local/lib/python3.7/site-packages/seaborn/categorical.py", line 3149, in barplot
    errcolor, errwidth, capsize, dodge)
  File "/usr/local/lib/python3.7/site-packages/seaborn/categorical.py", line 1608, in __init__
    self.establish_colors(color, palette, saturation)
  File "/usr/local/lib/python3.7/site-packages/seaborn/categorical.py", line 315, in establish_colors
    lum = min(light_vals) * .6
ValueError: min() arg is an empty sequence
```

**Comment by akashsara** [comment]
Heya,

Can you check whether an excel sheet has been generated in the /output directory? Judging by the Traceback, I think there's an issue with the graphing function. My best guess right now is that the date format is a little different than what was coded. 

If the excel sheet has been generated, could you check if the dates entry has any values? If my suspicions are right, it will be an empty sheet. In which case, the format in which the WhatsApp chat is in is different from what I've seen before. 

These are the supported formats:

```
18/05/16, 7:06:22 PM: ‪(username/phone number): message
4/24/17, 6:30 PM - (username/phone number): message
```

If it's in a different format, let me know and I'll update the code to support it.

**Comment by coisnepe** [comment]
Oh so that might be why. Here's a sample line:

```
[30/04/2015 20:55:13] coisnepe: My message
```

**Comment by akashsara** [comment]
Heya,

I've modified the code and hopefully it should be fixed now. Try pulling the latest changes/cloning this repo again and running the code. Do let me know if there are any issues.

**Comment by akashsara** [comment]
Closing this issue. Feel free to reopen it if the update isn't working for you.
