### ISSUE TITLE
Output folder

### ISSUE THREAD

**Issue by lucas-ubm** [akashsara/whatsapp-message-analysis#5]
Maybe this is more of a comment than an issue since I found a solution.

If you don't create an output folder the script won't work. Maybe including this on the readme or already including an empty output folder will ease this for people with less technical expertise.

**Comment by akashsara** [comment]
I've added some code to fix this. Now it checks for the output folder before creating any new files in the folder. Thanks for the info, let me know if there's any other problems. :)
